use_frameworks!

target 'DuckDate-iOS' do
  platform :ios, '8.0'
  pod 'DuckDate', :path => '..'
end

target 'DuckDate-Tests' do
  platform :ios, '8.0'
  pod 'DuckDate', :path => '..'
end

target 'DuckDate-macOS' do
  platform :osx, '10.11'
  pod 'DuckDate', :path => '..'
end
