use_frameworks!

abstract_target "DuckDate" do
  pod 'DuckDate', :path => '..'
  
  target 'DuckDate-iOS'
  target 'DuckDate-macOS'
  target 'DuckDate-Tests'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end
