# References:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8

before_install:
- gem install cocoapods --no-ri --no-rdoc

script:
- set -o pipefail && xcodebuild test -workspace Example/DuckDate.xcworkspace -scheme DuckDate-iOS -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -workspace Example/DuckDate.xcworkspace -scheme DuckDate-macOS -sdk macosx10.11 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
